import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>

     fsdf
    </div>
  )
}

export default Home
